
services:
  - name: host
    project: ..\src\HelpDesk.Host\HelpDesk.Host.csproj
    bindings:
      - name: http
        port: 8765
        protocol: http
    env:
      - name: ASPNETCORE_ENVIRONMENT
        value: Development 
  - name: core
    project: ..\src\HelpDesk.Core\HelpDesk.Core.csproj
    env:
      - name: DOTNET_ENVIRONMENT
        value: Development 
  - name: db
    image: postgres:14-alpine
    bindings:
    - port: 5432
    volumes:
    - source: ../.postgres
      target: /var/lib/postgresql/data
    env:
      - name: POSTGRES_PASSWORD
        value: helpDesk
      - name: POSTGRES_USER
        value: helpDesk
      - name: POSTGRES_DB
        value: helpDesk